crawler:
  start_url: "https://guide.rolg.maxion.gg"
  max_depth: 2
  domain: "guide.rolg.maxion.gg"
  max_concurrent: 10
  timeout: 10
  max_retries: 3
  delay_between_requests: 1.0

chunker:
  max_chunk_size: 1000
  overlap_size: 100
  language: "mixed"

vector_db:
  model_name: "all-MiniLM-L6-v2"
  database_path: "data/vector_db"
  use_gpu: false
  index_type: "flat"
  cache_size: 1000

llm:
  model_name: "gemini-1.5-flash"
  max_tokens: 1000
  temperature: 0.7
  translation_cache_size: 1000

logging:
  level: "INFO"
  log_dir: "logs"
  log_file: "rag_system.log"
  max_file_size: "10MB"
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"